const assets = [
	{
	"id":"achievments",
	"url":"assets/json\\achievments.json"
	},
	{
	"id":"baseGameConfigFairy",
	"url":"assets/json\\baseGameConfigFairy.json"
	},
	{
	"id":"baseGameConfigHumans",
	"url":"assets/json\\baseGameConfigHumans.json"
	},
	{
	"id":"fairies",
	"url":"assets/json\\fairies.json"
	},
	{
	"id":"baseGameConfigMonster",
	"url":"assets/json\\baseGameConfigMonster.json"
	},
	{
	"id":"humans",
	"url":"assets/json\\humans.json"
	},
	{
	"id":"localization_DE",
	"url":"assets/json\\localization_DE.json"
	},
	{
	"id":"localization_EN",
	"url":"assets/json\\localization_EN.json"
	},
	{
	"id":"localization_FR",
	"url":"assets/json\\localization_FR.json"
	},
	{
	"id":"localization_ES",
	"url":"assets/json\\localization_ES.json"
	},
	{
	"id":"localization_IT",
	"url":"assets/json\\localization_IT.json"
	},
	{
	"id":"localization_JA",
	"url":"assets/json\\localization_JA.json"
	},
	{
	"id":"localization_KO",
	"url":"assets/json\\localization_KO.json"
	},
	{
	"id":"localization_PT",
	"url":"assets/json\\localization_PT.json"
	},
	{
	"id":"localization_RU",
	"url":"assets/json\\localization_RU.json"
	},
	{
	"id":"localization_TR",
	"url":"assets/json\\localization_TR.json"
	},
	{
	"id":"localization_ZH",
	"url":"assets/json\\localization_ZH.json"
	},
	{
	"id":"monsters",
	"url":"assets/json\\monsters.json"
	},
	{
	"id":"resources",
	"url":"assets/json\\resources.json"
	},
	{
	"id":"modifyers",
	"url":"assets/json\\modifyers.json"
	}
];

export default assets;
